name: django-env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.15=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.13=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py311h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=hd233ad5_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.10.0
      - asgiref==3.9.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.5
      - cachetools==5.5.2
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - cryptography==46.0.3
      - django==4.2.26
      - django-allauth==65.13.0
      - django-cors-headers==4.8.0
      - django-csp==4.0
      - django-mongodb-backend==5.2.2
      - django-mongoengine==0.5.6
      - django-rest-framework-mongoengine==3.4.1
      - djangorestframework==3.16.1
      - djangorestframework-simplejwt==5.5.1
      - dnspython==2.8.0
      - frozenlist==1.7.0
      - google==3.0.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.181.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.3
      - google-genai==1.49.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - grpcio==1.74.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httplib2==0.30.2
      - httpx==0.28.1
      - idna==3.10
      - mongoengine==0.29.1
      - multidict==6.6.4
      - oauthlib==3.3.1
      - packaging==25.0
      - pillow==11.3.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyjwt==2.10.1
      - pymongo==4.14.1
      - pyparsing==3.2.3
      - python-decouple==3.8
      - python-dotenv==1.1.1
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - simplejwt==2.0.1
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlparse==0.5.3
      - tenacity==9.1.2
      - tqdm==4.67.1
      - typing==3.7.4.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - websockets==15.0.1
      - yarl==1.22.0
prefix: /home/venleonin/miniconda3/envs/django-env
